public class AssetWrapper {
    // used to parse Asset API response
    public String vin;
    public String vehicleNum;
    public String vehicleRegNum;
    public String regNumCountryKey;
    public String oemVin;
    public String manufacturer;
    public String prodCode;
    public String modelRange;
    public String vehicleType;
    public String typeVariant;
    public String deliveryExWorkDate;
    public String firstRegDate;
    public String wheelBase;
    public String overhang;
    public String suspension;
    public String truckAxle;
    public String customerRegDate;
    public String customerNo;
    public String customerName; 
}